import Link from "next/link";
import { getActiveWorkspace } from "@/lib/workspace-context";
import {
  getWeeklySummaryByWeek,
  listWeeklySummaries,
} from "@/lib/summaries";
import { APP_TIMEZONE, formatDateLabel, isValidDateParam } from "@/lib/dates";
import { MarkdownView } from "../meetings/[id]/markdown-view";

export const dynamic = "force-dynamic";

function weekLabel(weekStart: string): string {
  const [y, m, d] = weekStart.split("-").map(Number);
  return new Intl.DateTimeFormat("en-US", {
    timeZone: "UTC",
    month: "short",
    day: "numeric",
    year: "numeric",
  }).format(new Date(Date.UTC(y, m - 1, d, 12)));
}

function formatGenerated(d: Date): string {
  return new Intl.DateTimeFormat("en-US", {
    timeZone: APP_TIMEZONE,
    month: "short",
    day: "numeric",
    hour: "numeric",
    minute: "2-digit",
  }).format(d);
}

// Weekly "Sunday Summary" briefings, written by the local runner
// (tools/sunday-summary) and pushed via PUT /api/v1/summaries. Always in the
// nav — a workspace the runner skips just shows the empty state.
export default async function SummariesPage({
  searchParams,
}: {
  searchParams: Promise<{ week?: string }>;
}) {
  const { week } = await searchParams;
  const workspace = await getActiveWorkspace();
  const summaries = await listWeeklySummaries(workspace.id);

  const selectedWeek =
    isValidDateParam(week) && summaries.some((s) => s.weekStart === week)
      ? week
      : summaries[0]?.weekStart;
  const selected = selectedWeek
    ? await getWeeklySummaryByWeek(workspace.id, selectedWeek)
    : undefined;

  return (
    <div className="page">
      <div className="page-head">
        <div>
          <h1 className="page-title">Summaries</h1>
          <p className="muted page-subtitle">
            Your Sunday Summary — a weekly briefing for the week ahead,
            generated by the local agent.
          </p>
        </div>
        {summaries.length > 1 && (
          <div className="range-toggle">
            {summaries.map((s) => (
              <Link
                key={s.id}
                href={`/summaries?week=${s.weekStart}`}
                className={`range-btn ${s.weekStart === selectedWeek ? "is-active" : ""}`}
              >
                {weekLabel(s.weekStart)}
              </Link>
            ))}
          </div>
        )}
      </div>

      {!selected ? (
        <p className="muted empty">
          No summaries yet. The Sunday-Summary agent hasn&rsquo;t pushed one for
          this workspace — see <code>tools/sunday-summary/README.md</code> to
          set it up, or add this workspace to its config.
        </p>
      ) : (
        <article className="summary-view">
          <p className="muted summary-meta">
            Week of {formatDateLabel(selected.weekStart)} · generated{" "}
            {formatGenerated(selected.generatedAt)}
            {selected.model ? ` · ${selected.model}` : ""}
          </p>
          <MarkdownView markdown={selected.markdown} />
        </article>
      )}
    </div>
  );
}
